<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="basicfamily" nsURI="http://www.eclipse.org/sirius/sample/basicfamily"
    nsPrefix="basicfamily">
  <eAnnotations source="sirius">
    <details key="iconFolder" value="uk.ac.york.aconite.family/icons/"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Person" abstract="true">
    <eAnnotations source="sirius.diagram">
      <details key="name" value="Relationships"/>
    </eAnnotations>
    <eAnnotations source="sirius.node">
      <details key="name" value="Rel Default"/>
      <details key="abstract" value="true"/>
      <details key="color" value="white"/>
      <details key="showIcon" value="true"/>
      <details key="childrenPresentation" value="List"/>
    </eAnnotations>
    <eAnnotations source="sirius.container">
      <details key="extend" value="Rel Default"/>
      <details key="name" value="Person"/>
      <details key="sce" value=""/>
      <details key="foregroundColor" value="light_green"/>
      <details key="container" value="Relationships"/>
    </eAnnotations>
    <eAnnotations source="sirius.border">
      <details key="extend" value="Rel Default"/>
      <details key="sce" value="parents"/>
      <details key="name" value="Parent"/>
      <details key="container" value="Person"/>
    </eAnnotations>
    <eAnnotations source="sirius.node">
      <details key="extend" value="Rel Default"/>
      <details key="name" value="Child"/>
      <details key="container" value="Person"/>
    </eAnnotations>
    <eAnnotations source="sirius.container">
      <details key="extend" value="Rel Default"/>
      <details key="name" value="Siblings"/>
      <details key="sce" value=""/>
      <details key="labelValue" value="Siblings"/>
      <details key="foregroundColor" value="light_yellow"/>
      <details key="container" value="Relationships"/>
      <details key="showIcon" value="false"/>
    </eAnnotations>
    <eAnnotations source="sirius.node">
      <details key="name" value="Sibling"/>
      <details key="container" value="Siblings"/>
      <details key="sce" value="parents.children->excluding(self)"/>
      <details key="showIcon" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Person" eOpposite="#//Person/parents">
      <eAnnotations source="sirius.edge">
        <details key="name" value="SiblingsEdge"/>
        <details key="creatable" value="false"/>
        <details key="labelExpression" value=""/>
        <details key="color" value="gray"/>
        <details key="container" value="Relationships"/>
        <details key="targetFinderExpression" value="aql:self"/>
        <details key="sourceNode" value="Person"/>
        <details key="targetNode" value="Siblings"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parents" upperBound="2"
        eType="#//Person" eOpposite="#//Person/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mother" eType="#//Woman"
        derived="true">
      <eAnnotations source="sirius.edge">
        <details key="reconnectable" value="false"/>
        <details key="name" value="Mother"/>
        <details key="container" value="Family"/>
        <details key="sourceNode" value="Man, Woman"/>
        <details key="labelExpression" value=""/>
        <details key="color" value="purple"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="father" eType="#//Man"
        derived="true">
      <eAnnotations source="sirius.edge">
        <details key="extend" value="Mother"/>
        <details key="name" value="Father"/>
        <details key="color" value="blue"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Family">
    <eAnnotations source="sirius.diagram">
      <details key="name" value="Family"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//Person" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Man" eSuperTypes="#//Person">
    <eAnnotations source="sirius.container">
      <details key="name" value="Man"/>
      <details key="container" value="Family"/>
      <details key="shape" value="image"/>
      <details key="imagePath" value="man.svg"/>
      <details key="borderSize" value="0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Woman" eSuperTypes="#//Person">
    <eAnnotations source="sirius.node">
      <details key="extend" value="Man"/>
      <details key="name" value="Woman"/>
      <details key="imagePath" value="woman.svg"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
